#!/usr/bin/env ruby
# This script will initialize a Ripl shell with a brewer instantiated
require 'ripl'

# pull in our src
require_relative "src/git"
require_relative "src/brewer"

# Clone the repo
manager = RepoManager.new
manager.clone

# Start up a brewer
brewer = Brewer.new

# Start the ripl shell
Ripl.start :binding => binding
# Start brewing
