require 'pry'
require "require_all"
require 'git'
require 'fileutils'
require 'slack-notifier'
require 'yaml'
require 'yaml/store'
require 'net/ping'
require 'wannabe_bool'
require 'terminal-table'
require "rainbow"
require 'rack-flash'
require 'sinatra/base'
